spring:
  profile:
    active: DEV
  application:
    name: Enterprise

  datasource:
    url: jdbc:postgresql://localhost:5432/enterprise
    username: postgres
    password: password

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
        format_sql: true
  mvc:
    format:
      date-time: iso

  liquibase:
    enabled: false
    change-log: "classpath:/liquibase/changelog-master.yaml"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8181

debug: false

logging:
  level:
    liquibase: INFO
    org:
      springframework: INFO
    com:
      knits:
        enterprise: DEBUG
